version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      # Hanya diekspos ke localhost (VPS internal) di port 3080 agar tidak bentrok
      - "127.0.0.1:3080:80"
    depends_on:
      - pocketbase
    restart: unless-stopped

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    volumes:
      - pb_data:/app/pb_data
    restart: unless-stopped

volumes:
  pb_data:
